config/routes.rb
Btc1k::Application.routes.draw do

  get '/status', to: 'status#index', as: 'status_index'
  get '/status/:btc_address', to: 'status#show', as: 'status_request'
  post '/verify', to: 'status#verify', as: 'status_verify'

  resources :payment_requests, only: [:create, :new]

  get '/how_to', to: 'payment_requests#how_to', as: 'how_to'
  get '/imprint', to: 'payment_requests#impress', as: 'impress'
  root 'payment_requests#how_to'
end

app/models/bits_of_proof.rb
require 'rest_client'
module BitsOfProof

  class Payment
    @username= Btc1k::Application.config.bits_of_proof_username
    @pass= Btc1k::Application.config.bits_of_proof_pass
    API_BASE_URI = 'https://api.bitsofproof.com/mbs/1/'

    def self.init(bitcoin_address)
      RestClient.log = '/tmp/restclient.log'
      uri = 'paymentRequest'

      params = {
        amount: 100000000,
        confirmations: 1,
        timeout: "P2D",
        title: bitcoin_address,
        callbackUrl: "http://api.bitsofproof.com:8280/btc1k/payment"
      }.to_json

      begin
        resource = RestClient::Resource.new(API_BASE_URI + uri, user: @username, password: @pass)
        response = JSON.load(resource.post params, content_type: :json, accept: :json, user_agent: 'btc1k')
      rescue  => e
        e.response
      end
    end

    def self.get_payment_requests
      uri = "/paymentRequest"

      begin
        resource = RestClient::Resource.new(API_BASE_URI + uri , user: @username, password: @pass)
        response = JSON.load(resource.get)
      rescue  => e
        e.response
      end
    end

    def self.get_payment_request(payment_id)
      uri = "/paymentRequest"

      begin
        resource = RestClient::Resource.new(API_BASE_URI + uri , user: @username, password: @pass)
        response = JSON.load(resource[payment_id].get)
      rescue  => e
        e.response
      end
    end
  end
end

app/models/payment_request.rb
class PaymentRequest < ActiveRecord::Base
  validates :btc_address, bitcoin_address: true



  def self.get_payment_request_struct(payment_id)
    bop_api_call = BitsOfProof::Payment.get_payment_request(payment_id)
    request_struct = Struct.new(:id, :created_at, :address, :confirmations,
                                :timeout, :paid, :state, :provision_address,
                                :title, :payment_qr_link)


    request_struct.new(bop_api_call["id"], bop_api_call["createdAt"], bop_api_call["address"],
                       bop_api_call["confirmations"], bop_api_call["timeout"], 
                       bop_api_call["paid"], bop_api_call["state"], bop_api_call["provisionAddress"], 
                       bop_api_call["title"], bop_api_call["_links"]["bip72"]["href"])

  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

end

app/controllers/payment_requests_controller.rb
class PaymentRequestsController < ApplicationController
  # before_action :set_payment_request, only: [:show, :status]
  # before_action :set_request_struct, only: [:show, :status]

  # GET /payment_requests
  # def index
  # end

  # # GET /payment_requests/1
  # def show
  #   if @request_struct.state == "PENDING"
  #     @qr = RQRCode::QRCode.new(@request_struct.payment_qr_link, size: 6)
  #   else
  #     redirect_to payment_request_status_path(btc_address: @payment_request.btc_address)
  #   end
  # end

  # GET /payment_requests/new
  def new
    @payment_request = PaymentRequest.new
  end

  def create
    @payment_request = PaymentRequest.find_or_initialize_by(payment_request_params)
    if @payment_request.new_record?
      ## Creating a new bop payment_request and save the importand values in
      #  @payment_request
      bop_api_call = BitsOfProof::Payment.init(@payment_request.btc_address)
      @payment_request.bop_payment_id = bop_api_call["id"]
    end
    if @payment_request.save
      redirect_to  status_request_url(@payment_request.btc_address)
    else
      render action: 'new'
    end
  end

  def status
    unless @payment_request
      redirect_to root_url(@paymen_request), notice: "Your paperwallet address is invalid"
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    # def set_payment_request
    #   @payment_request = PaymentRequest.find_by(btc_address: params[:btc_address])
    # end

    # def set_request_struct
    #   if @payment_request
    #     @request_struct = PaymentRequest.get_payment_request_struct(@payment_request.bop_payment_id)
    #   end
    # end

    # Only allow a trusted parameter "white list" through.
    def payment_request_params
      params.require(:payment_request).permit(:btc_address)
    end
end

app/controllers/status_controller.rb
class StatusController < ApplicationController
  before_action :set_payment_request, only: [:show]
  before_action :set_verify_payment_request, only: [ :verify ]
  before_action :set_request_struct, only: [:show, :verify]

  def show
    if @request_struct.state == "PENDING"
      @qr = RQRCode::QRCode.new(@request_struct.payment_qr_link, size: 6)
    end
  end

  def verify
    if @payment_request
      redirect_to status_request_url(btc_address: @payment_request.btc_address)
    else
      redirect_to status_index_url, notice: "Your ticket address is invalid"
    end
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_payment_request
      @payment_request = PaymentRequest.find_by(btc_address: params[:btc_address])
    end

    def set_verify_payment_request
      @payment_request = PaymentRequest.find_by(verify_params)
    end

    def set_request_struct
      if @payment_request
        @request_struct = PaymentRequest.get_payment_request_struct(@payment_request.bop_payment_id)
      end
    end

    def verify_params
      params.require(:payment_request).permit(:btc_address)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/application/_flashes.html.erb
<div id="flash">
  <% flash.each do |key, value| -%>
    <div id="flash_<%= key %>"><%= value %></div>
  <% end -%>
</div>

app/views/application/_javascript.html.erb
<%= javascript_include_tag :application %>

<%= yield :javascript %>

<% if Rails.env.test? %>
  <%= javascript_tag do %>
    $.ajaxSetup({ async: false });
  <% end %>
<% end %>

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:charset => "utf-8"}/
    %meta{:content => "NOODP", :name => "ROBOTS"}/
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    %title= page_title
    = stylesheet_link_tag :application, :media => 'all'
    = csrf_meta_tags
  %body{:class => body_class}
    = render 'flashes'
    %header.main
      .wrapper
        %nav.actions
          =link_to "How it works", how_to_path
          =link_to "Verify ticket status",  status_index_path
          -# = form_tag("/status", method: "get") do
            = label_tag(:btc_address, "Get status for your ticket")
            = text_field_tag(:btc_address)
            = submit_tag("check")
        %h1
          %span
            <a href="/" onclick="return confirm('Leave this page? After leaving this page we generate a new ticket address')">Btc1k</a>
            -# BTC1K Party ticket purchase
    :javascript
      (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
      (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
      m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
      })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

      ga('create', 'UA-46302180-2', 'btc1k.com');
      ga('send', 'pageview');

    %section.container
      = yield
    %footer.main
      .wrapper
        %p
          BTC1K party is maintained and funded by
          = succeed "." do
            %a{:href => "https://btc1k.com"} 600watt, cheech300, bulleric
          Questions? Tweet
          = succeed "." do
            %a{:href => "http://www.twitter.com/btc1k"} @btc1k
        %p Copyright © 2013 BTC1K
        %p
        %p 
          Special thanks to
        %p 
          = link_to "http://bitsofproof.com", target: "_blank" do
            = image_tag "bitsofproof.png"
        %p 
          = link_to "Imprint", impress_url
    = render 'javascript'

app/views/payment_requests/_form.html.haml
= form_for @payment_request do |f|
  - if @payment_request.errors.any?
    .error_messages
      %h2
        = pluralize(@payment_request.errors.count, "error")
        prohibited this user from being saved:
      %ul
        - @payment_request.errors.full_messages.each do |msg|
          %li= msg
  .field
    -# = f.label :btc_address
    = f.hidden_field :btc_address
    -# = f.text_field :btc_address, placeholder: "Paste your paperwallet address here", disabled: true
  .action
    = f.submit t(".continue"), class: "big", id: "pay_your_coin", data: {confirm: "!!!We have no access to your private key. Make sure your paperwallet has been printed!!!"}, style: "display: none;"

app/views/payment_requests/edit.html.haml
%header.main
  .wrapper
    %h1
      BTC1K Party ticket purchase
%section.howto
  .wrapper
    %article.paperwallet
      %h3 1. Create a paperwallet
      %p
        Create a new and empty paperwallet. Make it private or create one at bitaddress or paperwallet.btc1k.com. Make sure it is empty.
    %article.request
      %h3 2. Get payment address
      %p
        Fill your address to the form below and request a payment. You will get a new payment address.
    %article.pay
      %h3 3. Pay your bitcoin
      %p
        Send 1 btc to this address. Later an amount of bitcoins will be transfered to your paperwallet.
%section.form
  .wrapper
    %h2
      = link_to "PAYMENT ADDRESS"
%section.info
  .wrapper
    In combination with the transaction in the blockchain your ticket will be valid. Don't spend the milibitcoins from your paperwallet.

app/views/payment_requests/how_to.html.haml
%header.main
  .wrapper
    %h1
      BTC1K Party ticket ipo
%section.howto
  .wrapper
    %article.paperwallet
      %h3
        = t(".first_step.headline")
      %p
        = t(".first_step.description")
    %article.request
      %h3
        = t(".second_step.headline")
      %p
        = t(".second_step.description")
    %article.request

    %article.pay
      %h3
        = t(".third_step.headline")
      %p
        = t(".third_step.description")

%section.form
  .wrapper
    %h2
      = link_to "Create your ticket for the BTC1k Party", new_payment_request_path
%section.info
  .wrapper
    = t("global.transactioninfo")

app/views/payment_requests/impress.html.haml
%header.main
  .wrapper
    %h1
      Imprint 
%section.content
  .wrapper
    %article.company
      %h3 BTC1K UG (haftungsbeschränkt) in Gründung
      %P CEO Eric Sidibe, Timo Strohmenger
      %p Elisabethenstraße 34
      %p 64283 Darmstadt
      %p info@btc1k.com

%section.form
  .wrapper
    %h2
      = link_to "Create your ticket for the BTC1k Party", new_payment_request_path
%section.info
  .wrapper
    = t(".transactioninfo")

app/views/payment_requests/new.html.haml
= stylesheet_link_tag('print', :media => :print)
%section.paperwallet
  .wrapper
    = render "shared/bitaddress"
    .print
      %h3=t(".titles.paperwallet")
      %p
        =t(".text.paperwallet")

      %input#paperprint{:name => "print", :onclick => "window.print(); document.getElementById('pay_your_coin').style.display='inline'; document.getElementById('payment_info').style.display='none'", :type => "submit", :value => t(".print"), class: "print-now"}



%section.info#payment_info
  .wrapper
    %p Payment button will appear after you printed the paperwallet/ticket

%section.form
  .wrapper
    =render "form"

%section.info
  .wrapper
    = t(".text.transactioninfo")

app/views/shared/_bitaddress.html.erb
<!-- Customized Bitaddress.org implementation
Donation Address: 1NiNja1bUmhSoTXozBRBEtR8LeF9TGbZBN

Notice of Copyrights and Licenses:
***********************************
The bitaddress.org project, software and embedded resources are copyright bitaddress.org (pointbiz). 
The bitaddress.org name and logo are not part of the open source license.

Portions of the all-in-one HTML document contain JavaScript codes that are the copyrights of others. 
The individual copyrights are included throughout the document along with their licenses.
Included JavaScript libraries are separated with HTML script tags.

Summary of JavaScript functions with a redistributable license:
JavaScript function		License
*******************		***************
Array.prototype.map		Public Domain
window.Crypto			BSD License
window.SecureRandom		BSD License
window.EllipticCurve		BSD License
window.BigInteger		BSD License
window.QRCode			MIT License
window.Bitcoin			MIT License
window.Crypto_scrypt		MIT License

The bitaddress.org software is available under The MIT License (MIT)
Copyright (c) 2011-2013 bitaddress.org (pointbiz)

Permission is hereby granted, free of charge, to any person obtaining a copy of this software and 
associated documentation files (the "Software"), to deal in the Software without restriction, including 
without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or 
sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject 
to the following conditions:

The above copyright notice and this permission notice shall be included in all copies or substantial 
portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT 
LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. 
IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, 
WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE 
SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.

GitHub Repository: https://github.com/pointbiz/bitaddress.org
-->

<%= javascript_include_tag "bitaddress" %>

<div class="bitaddress"  onclick="SecureRandom.seedTime();" onkeypress="SecureRandom.seedTime();" onmousemove="ninja.seeder.seed(event);">
	<div id="busyblock"></div>
	<div id="main">
		<div id="testnet"></div>
		
		<div id="generate">
			<span id="generatelabelbitcoinaddress">Generating Bitcoin Address...</span><br />
			<span id="generatelabelmovemouse">MOVE your mouse around to add some extra randomness...</span><br />
		</div>

		<div id="wallets">
			<div id="paperarea">
				<div class="commands">
					<div id="papercommands" class="row">
						<span><label id="paperlabelhideart">Hide Art?</label> <input type="checkbox" id="paperart" onchange="ninja.wallets.paperwallet.toggleArt(this);" /></span>
						<span><label id="paperlabeladdressestogenerate">Addresses to generate:</label> <input type="text" id="paperlimit" /></span>
						<span><input type="button" id="papergenerate" value="Generate" onclick="ninja.wallets.paperwallet.build(document.getElementById('paperlimit').value * 1, document.getElementById('paperlimitperpage').value * 1, !document.getElementById('paperart').checked, document.getElementById('paperpassphrase').value);" /></span>
					</div>
					<div id="paperadvancedcommands" class="row extra">
						<span><label id="paperlabelencrypt">BIP38 Encrypt?</label> <input type="checkbox" id="paperencrypt" onchange="ninja.wallets.paperwallet.toggleEncrypt(this);" /></span>
						<span><label id="paperlabelBIPpassphrase">Passphrase:</label> <input type="text" id="paperpassphrase" /></span>
						<span><label id="paperlabeladdressesperpage">Addresses per page:</label> <input type="text" id="paperlimitperpage" /></span>
					</div>
				</div>
				<div id="paperkeyarea"></div>
			</div>
		</div>
	</div>

<%= javascript_include_tag "bitaddress_footer_load" %>
</div>

app/views/status/_form.html.haml
= form_for :payment_request, url: status_verify_path do |f|

  .field
    = f.label :btc_address
    = f.text_field :btc_address, placeholder: t(".placeholder")
  .action
    = f.submit t(".continue"), class: "big"

app/views/status/index.html.haml
%section.form
  .wrapper
    %h1=t(".title")
    %p
      =t(".text")

    =render 'form'

%section.info
  .wrapper
    = t("global.transactioninfo")

app/views/status/show.html.haml
%section.status
  .wrapper
    - if (@request_struct.state == "PENDING")
      %h1.status_title
        =t(".titles.pending")
      -# %h2
      -#   %pre
      -#     =@request_struct.title
      %p=t(".text.pending")

    - elsif (@request_struct.state == "CLAIMED")
      %h1=t(".titles.claimed", address: @request_struct.title)

      %h2
        %pre
          =@request_struct.title
      %p=t(".text.claimed")

    - elsif (@request_struct.state == "TIMEOUT")
      %h1=t(".titles.timeout", address: @request_struct.title)
      %h2
        %pre
          =@request_struct.title
      %p=t(".text.timeout")

    - if (@request_struct.state == "PENDING")
      %dl
        %dt
          %h4
            Payment address
          %pre
            #{@request_struct.address}
        %dd
          %table.qrcode
            - @qr.modules.each_index do |x|
              %tr
                - @qr.modules.each_index do |y|
                  - if @qr.dark?(x,y)
                    %td.black
                  - else
                    %td.white
    %dl
      %dt
        Status
      %dd
        #{@request_struct.state}

    %p= link_to "watch your transaction in blockchain.info", "https://blockchain.info/address/" + @request_struct.address, target: "_blank"
    %p= link_to "create another ticket", new_payment_request_path, target: "_blank"

%section.info
  .wrapper
    %p= t("global.transactioninfo")
    %p
      Your paperwallet address: 
      = @request_struct.title

app/views/status/status.html.haml
%section.status
  .wrapper
    %h3
      %b
        STATUS:
      #{@request_struct.state}
    %p
      ID: #{@request_struct.id}
    %p
      CREATET_AT: #{@request_struct.created_at}
    %p
      ADDRESS: #{@request_struct.address}
    %p
      CONFIRMATIONS: #{@request_struct.confirmations}
    %p
      TIMEOUT: #{@request_struct.timeout}
    %p
      PAID: #{@request_struct.paid}
    %p
      PROVISION_ADDRESS: #{@request_struct.provision_address}
    %b
      %p= link_to "watch your transaction in blockchain.info", "https://blockchain.info/address/" + @request_struct.provision_address , target: "_blank"
      %p
        = link_to "create another ticket", new_payment_request_path, target: "_blank"
        %p